### ISSUE TITLE
I need to join, quick, my repo isn't here

### ISSUE THREAD

**Issue by hugo4715** [JoinDevathon/Questions#21]
Can you please give me access to a repo, i almost finished my plugin.
Thanks

**Comment by 28andrew** [comment]
You didn't signup before it started.

**Comment by OutdatedVersion** [comment]
Sorry, but it's over @hugo4715. Next year maybe?

**Comment by hugo4715** [comment]
If next year you allow me to post my plugin.......

**Comment by 28andrew** [comment]
**YOU HAVE TO signup before it starts**
